# 启动端口号
server:
  post: 8000

# MySQL数据源配置
mysql:
  username: root
  password: 123456789
  url: tcp(localhost:3306)/mall?charset=utf8&parseTime=True&loc=Local

# 图片路径配置
upload:
  save-path: /Users/zchengo/resource/images/
  access-url: http://localhost:8000/image/

# JWT配置
jwt:
  signing-key: z3d6k8v0n3w7m9sa1fd0u09h